version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storage-service
    ports:
      - '5432:5432'
    networks:
      - database
# Networks to be created to facilitate communication between containers
networks:
  database:
    driver: bridge